### PR TITLE
Implementing Hydrogen

### PR DESCRIPTION
**Pull request by minhh2792**

### CODE REVIEW

**Comment by wuangg** [comment]
Hydrogen has discontinued its development and recommended us using FerriteCore since both coremods having similarities in goals and features. Therefore, it's worth to implement FerriteCore for even better performance and compatibility in upcoming Minecraft versions.

https://github.com/malte0811/FerriteCore

**Comment by minhh2792** [comment]
Hydrogen is still works fine tho, but hey, I already take a look on FerriteCore and will working on implement it soon 😳

**Comment by minhh2792** [comment]
> > Hydrogen is still works fine tho, but hey, I already take a look on FerriteCore and will working on implement it soon flushed
> 
> I'm pretty sure they work together too

No it's not, FerriteCore is incompatible with Hydrogen

**Comment by yavko** [comment]
> > > Hydrogen is still works fine tho, but hey, I already take a look on FerriteCore and will working on implement it soon flushed
> > 
> > 
> > I'm pretty sure they work together too
> 
> No it's not, FerriteCore is incompatible with Hydrogen

Worked for me when I was using fabric on the client.

**Comment by KurumiFake** [comment]
Screenshot_2022-04-14-06-14-43-16
it *used to* work

**Pull request merged**
